// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC91gwDoqVGxFnrpqyeJSXI8bvu5PuOmrk',
    appId: '1:1039669549684:web:9e8ff269585eaca9f48f21',
    messagingSenderId: '1039669549684',
    projectId: 'sif-project-c2422',
    authDomain: 'sif-project-c2422.firebaseapp.com',
    storageBucket: 'sif-project-c2422.appspot.com',
    measurementId: 'G-QQ4ND793CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLkoWc0LfmE9WYpVB8wU0tQ-BXIV41m8',
    appId: '1:1039669549684:android:2b6b1f49aef6b288f48f21',
    messagingSenderId: '1039669549684',
    projectId: 'sif-project-c2422',
    storageBucket: 'sif-project-c2422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAziQUqRYPbSyKfWjsQvgBXFFL8aNLRwD0',
    appId: '1:1039669549684:ios:85e147a702cb1ae3f48f21',
    messagingSenderId: '1039669549684',
    projectId: 'sif-project-c2422',
    storageBucket: 'sif-project-c2422.appspot.com',
    iosBundleId: 'com.example.sif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAziQUqRYPbSyKfWjsQvgBXFFL8aNLRwD0',
    appId: '1:1039669549684:ios:9dbcea96d6c1b433f48f21',
    messagingSenderId: '1039669549684',
    projectId: 'sif-project-c2422',
    storageBucket: 'sif-project-c2422.appspot.com',
    iosBundleId: 'com.example.sif.RunnerTests',
  );
}
